### ISSUE TITLE
Performance (numba)

### ISSUE THREAD

**Issue by carderne** [carderne/gridfinder#4]
@sebastiantimwagner 
I never really found performance to be an issue running at native NTL resolution (~500m), even for multiple scenarios of huge countries (on beefy machines). But should be pretty straight-forward to wrap the `optimise()` function in `@numba`, would need to clean it up a bit first though (global state and things like that).

Some of the functions in `prepare.py` can be annoyingly slow, and many could probably be trivially sped up by using GDAL/OGR directly. But depending on what kind of scenarios, you're unlikely to run these many times so I never really bothered to look into it.

**Comment by sebastiantimwagner** [comment]
After some experiments today with some toy data and `numba`, I found some overhead from the kind of Just-in-Time compilation the library performs at runtime. It would be worthwhile to explore at which point there is a speed-up from using `numba` as compared for the problems `gridfinder` is dealing with.

When reading `prepare.py` I got some ideas how it could be improved. From executing `example.ipynb`, the roads preprocessing step seemed to be one of the slower parts of the pipeline and I collected a suggestion for speeding it up in this pull request: https://github.com/carderne/gridfinder/pull/5

I have some other ideas about where there might be room for optimization and will continue to create pull requests as I dig deeper into the code.

**Comment by carderne** [comment]
`drop_zero_pop()` is extremely clunky and slow, must be a smarter way of doing it using `numpy`/`sk-image`. (But it's not always necessary, depends what you're trying to do.)

**Comment by carderne** [comment]
Bunch of other stuff in `prepare.py` could probably also do with a clean. Lots of the NTL stuff may not be useful at all depending on how you're sourcing the imagery, and the upsampling in `prepare_ntl()` should be taken out into a separate function and only called if `upsample_by != 1`.

**Comment by carderne** [comment]
Another potential bottleneck is `raster_to_lines()`.

https://github.com/carderne/gridfinder/blob/a6848345f57139f4c35258266ca9feba1f9c650d/gridfinder/post.py#L104

It's just a very dumb for loop looking for pixels and adding them to a geometry, could probably be sped up quite easily. `GRASS` has a function to do this (`r.to.vect`), but I find GRASS quite hard to use in any repeatable/scriptable way. There might be other ways, but I haven't looked recently.
